name: App tests
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  app-tests:
    uses: owen2345/reusable-ci-cd-actions/.github/workflows/tests.yml@main
    with:
      prepare_db_cmd: null
      copy_env: false
      run_rubocop: true
      rspec_cmd: 'bundle exec rspec'
